/* Outreach Debate Florida — Instagram feed renderer
   Reads data/posts.json (regenerated by scripts/refresh-instagram.py)
   and renders a quiet grid of recent posts. */

document.addEventListener("DOMContentLoaded", () => {
  initInstagram();
});

async function initInstagram() {
  const grid = document.querySelector("[data-ig-grid]");
  if (!grid) return;

  try {
    const res = await fetch("data/posts.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    renderPosts(grid, data);
  } catch (err) {
    grid.innerHTML = `<p class="ig-empty">The field notes are being compiled — follow us directly on Instagram.</p>`;
  }
}

function renderPosts(grid, data) {
  if (!data.posts || !data.posts.length) {
    grid.innerHTML = `<p class="ig-empty">The field notes are being compiled — follow us directly on Instagram.</p>`;
    return;
  }

  const frag = document.createDocumentFragment();

  data.posts.forEach((post) => {
    const src = post.local || post.image_url;
    const cap = truncate(post.caption || "", 110);

    const card = document.createElement("a");
    card.className = "ig-card reveal";
    card.href = post.permalink || "https://www.instagram.com/outreachdebate.fl/";
    card.target = "_blank";
    card.rel = "noopener noreferrer";

    const img = document.createElement("img");
    img.src = src;
    img.alt = cap;
    img.width = 720;
    img.height = 900;
    img.loading = "lazy";
    img.decoding = "async";

    const capEl = document.createElement("span");
    capEl.className = "ig-cap";
    capEl.textContent = cap;

    const meta = document.createElement("span");
    meta.className = "ig-meta";
    meta.textContent = `${formatDate(post.timestamp)} · @outreachdebate.fl`;

    card.append(img, capEl, meta);
    frag.appendChild(card);
  });

  grid.innerHTML = "";
  grid.appendChild(frag);
  document.dispatchEvent(new CustomEvent("add-reveals"));
}

function truncate(text, max) {
  if (text.length <= max) return text;
  return text.slice(0, max).trimEnd() + "…";
}

function formatDate(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-US");
}