/* Outreach Debate Florida — Instagram feed renderer
   Reads data/posts.json (regenerated by scripts/refresh-instagram.py)
   and renders a responsive grid of recent posts. */

document.addEventListener("DOMContentLoaded", () => {
  initInstagram();
});

async function initInstagram() {
  const grid = document.querySelector("[data-ig-grid]");
  if (!grid) return;

  try {
    const res = await fetch("data/posts.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    renderPosts(grid, data);
  } catch (err) {
    grid.innerHTML = `<div class="ig-empty">Couldn't load the Instagram feed right now — check us out directly on Instagram.</div>`;
  }
}

function renderPosts(grid, data) {
  if (!data.posts || !data.posts.length) {
    grid.innerHTML = `<div class="ig-empty">New posts are on the way — follow us on Instagram to stay tuned.</div>`;
    return;
  }

  const frag = document.createDocumentFragment();

  data.posts.forEach((post, i) => {
    const src = post.local || post.image_url;
    const cap = truncate(post.caption || "", 110);

    const card = document.createElement("a");
    card.className = "ig-card reveal";
    card.setAttribute("data-delay", String(i % 3 + 1));
    card.href = post.permalink || "https://www.instagram.com/outreachdebate.fl/";
    card.target = "_blank";
    card.rel = "noopener noreferrer";

    const img = document.createElement("img");
    img.src = src;
    img.alt = cap;
    img.loading = "lazy";

    const overlay = document.createElement("div");
    overlay.className = "ig-card-overlay";

    const capEl = document.createElement("span");
    capEl.className = "ig-cap";
    capEl.textContent = cap;

    const meta = document.createElement("span");
    meta.className = "ig-meta";
    meta.textContent = `${formatDate(post.timestamp)} · @outreachdebate.fl`;

    overlay.append(capEl, meta);
    card.append(img, overlay);
    frag.appendChild(card);
  });

  grid.innerHTML = "";
  grid.appendChild(frag);
  dispatchReveal();
}

function dispatchReveal() {
  const event = new CustomEvent("add-reveals");
  document.dispatchEvent(event);
}

function truncate(text, max) {
  if (text.length <= max) return text;
  return text.slice(0, max).trimEnd() + "…";
}

function formatDate(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}